# report_gen.py — Generate professional HTML pentest report
# Usage: python report_gen.py

import json
from datetime import datetime

def generate_report(scan_file, cve_file, output_file="report.html"):
    """
    Read scan JSON + CVE JSON and generate HTML report.
    """
    # Load scan results
    with open(scan_file) as f:
        scan = json.load(f)

    # Load CVE findings
    with open(cve_file) as f:
        cves = json.load(f)

    # Count stats
    total_hosts  = len(scan['hosts'])
    total_ports  = sum(len(h['open_ports']) for h in scan['hosts'])
    total_cves   = len(cves)
    critical     = len([c for c in cves if c['severity'] == 'CRITICAL'])
    high         = len([c for c in cves if c['severity'] == 'HIGH'])

    # Build CVE rows
    cve_rows = ""
    for c in cves:
        color = {
            'CRITICAL': '#ff4757',
            'HIGH':     '#ffb347',
            'MEDIUM':   '#ffd700',
            'LOW':      '#00ff9d',
        }.get(c['severity'], '#ffffff')

        cve_rows += f"""
        <tr>
          <td>{c['port']}/tcp</td>
          <td>{c['banner'][:60]}</td>
          <td><span style="color:{color};font-weight:700">
              {c['severity']}</span></td>
          <td>{c['cve']}</td>
          <td>{c['desc']}</td>
          <td style="color:#82aaff">{c['msf']}</td>
        </tr>"""

    # Build host rows
    host_rows = ""
    for h in scan['hosts']:
        ports_str = ', '.join(str(p) for p in h['open_ports'])
        host_rows += f"""
        <tr>
          <td style="color:#00ff9d">{h['ip']}</td>
          <td>{len(h['open_ports'])}</td>
          <td>{ports_str}</td>
        </tr>"""

    # Build full HTML
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>NetScanner Report</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Orbitron:wght@700&display=swap');
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{background:#070b0f;color:#c8ffd4;font-family:'JetBrains Mono',monospace;padding:2rem}}
  h1{{font-family:'Orbitron',sans-serif;color:#00ff9d;font-size:22px;letter-spacing:3px;margin-bottom:4px}}
  h2{{color:#00ff9d;font-size:13px;letter-spacing:2px;margin:1.5rem 0 .75rem;text-transform:uppercase}}
  .meta{{color:#4a7a5a;font-size:11px;margin-bottom:2rem}}
  .stats{{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:2rem}}
  .stat{{background:#0f1419;border:0.5px solid #132213;border-radius:8px;padding:1rem;text-align:center}}
  .stat-val{{font-size:28px;font-weight:700;color:#00ff9d}}
  .stat-lbl{{font-size:10px;color:#4a7a5a;margin-top:4px;letter-spacing:1px}}
  .stat.red .stat-val{{color:#ff4757}}
  .stat.orange .stat-val{{color:#ffb347}}
  table{{width:100%;border-collapse:collapse;font-size:11px;margin-bottom:2rem}}
  th{{background:#0f1419;color:#4a7a5a;padding:8px 12px;text-align:left;letter-spacing:1px;font-size:10px;text-transform:uppercase;border-bottom:0.5px solid #132213}}
  td{{padding:8px 12px;border-bottom:0.5px solid #132213;vertical-align:top;line-height:1.5}}
  tr:hover td{{background:#0f1419}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700}}
  .footer{{color:#4a7a5a;font-size:10px;margin-top:2rem;border-top:0.5px solid #132213;padding-top:1rem}}
</style>
</head>
<body>
  <h1>NETSCANNER — PENTEST REPORT</h1>
  <div class="meta">
    Target: {scan['target']} &nbsp;|&nbsp;
    Scan Time: {scan['scan_time']} &nbsp;|&nbsp;
    Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &nbsp;|&nbsp;
    [!] For authorized testing only
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-val">{total_hosts}</div>
      <div class="stat-lbl">Live Hosts</div>
    </div>
    <div class="stat">
      <div class="stat-val">{total_ports}</div>
      <div class="stat-lbl">Open Ports</div>
    </div>
    <div class="stat">
      <div class="stat-val">{total_cves}</div>
      <div class="stat-lbl">CVEs Found</div>
    </div>
    <div class="stat red">
      <div class="stat-val">{critical}</div>
      <div class="stat-lbl">Critical</div>
    </div>
    <div class="stat orange">
      <div class="stat-val">{high}</div>
      <div class="stat-lbl">High</div>
    </div>
  </div>

  <h2>Discovered Hosts</h2>
  <table>
    <tr>
      <th>IP Address</th>
      <th>Open Ports</th>
      <th>Port List</th>
    </tr>
    {host_rows}
  </table>

  <h2>CVE Findings</h2>
  <table>
    <tr>
      <th>Port</th>
      <th>Banner</th>
      <th>Severity</th>
      <th>CVE</th>
      <th>Description</th>
      <th>Metasploit Module</th>
    </tr>
    {cve_rows}
  </table>

  <div class="footer">
    Generated by NetScanner v1.0 — Red Team Recon Toolkit &nbsp;|&nbsp;
    Aghori &nbsp;|&nbsp; {datetime.now().year}
  </div>
</body>
</html>"""

    with open(output_file, 'w') as f:
        f.write(html)

    print(f"[+] Report generated → {output_file}")
    print(f"[+] Open it in Firefox: firefox {output_file}")


if __name__ == "__main__":
    generate_report(
        scan_file="metasploitable.json",
        cve_file="cve_report.json",
        output_file="pentest_report.html"
    )